#!/bin/bash
#SBATCH --job-name=ft_coco_ytbdav
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=48G
#SBATCH --time=72:00:00
#SBATCH --output=logs/slurm/ft_coco_ytbdav_%j.out
#SBATCH --error=logs/slurm/ft_coco_ytbdav_%j.err

# Fine-tune COCO-pretrained MobileNetV2+KAN-SSM on joint YouTube-VOS + DAVIS.
# Mirrors the AOT PRE_YTB_DAV protocol:
#   - DAVIS (60 train seqs, dense annotations, hard scenes)
#   - YouTube-VOS (3471 train seqs, sparse annotations, diverse categories)
# WeightedRandomSampler ensures DAVIS = 25 % of every epoch.
#
# NOTE: limit_train_batches=3500 caps each epoch at 3500 optimizer steps
# (~1.17h train + ~0.25h val = ~1.42h/epoch on a single GPU).
# Without this, YouTubeVOS generates ~333k clips → one epoch takes ~14h.
# 3500 steps × batch_size=4 × accum=2 = 28000 clips seen per epoch.
# 50 epochs × 1.42h ≈ 71h (fits the 72h SLURM wall time).
#
# Starting weights: COCO pretrain checkpoint (DiagonalKANSSMCore, Phase 1 of protocol).
# Generated by pretrain_coco_sota_light.sh → checkpoints/best_coco_sota_light.ckpt.
# Loaded via +pretrained_weights (shape-safe partial transfer from train.py).
# Usage: export COMET_API_KEY=<key> && sbatch scripts/ft_coco_ytb_dav_50ep.sh

set -euo pipefail

PROJECT_ROOT="/home/WUR/stiva001/WUR/video_kamba"
cd "$PROJECT_ROOT"

if [ -d "venv" ]; then
    source venv/bin/activate
else
    echo "Error: venv not found." && exit 1
fi

export PYTHONPATH=.
export TMPDIR="${PROJECT_ROOT}/tmp"
export HF_HOME="${PROJECT_ROOT}/.cache/huggingface"
mkdir -p "$TMPDIR" "$HF_HOME" logs/slurm

# Load secrets from .env (never committed to git)
if [ -f "${PROJECT_ROOT}/.env" ]; then
    set -a; source "${PROJECT_ROOT}/.env"; set +a
fi

if [ -z "${COMET_API_KEY:-}" ]; then
    echo "Error: COMET_API_KEY not set. Add it to ${PROJECT_ROOT}/.env"
    exit 1
fi

# COCO pretrained checkpoint for DiagonalKANSSMCore (Phase 1 output)
# Generated by: sbatch scripts/pretrain_coco_sota_light.sh
CKPT="${PROJECT_ROOT}/checkpoints/best_coco_sota_light.ckpt"

if [ ! -f "$CKPT" ]; then
    echo "Error: COCO checkpoint not found at $CKPT"
    exit 1
fi

echo "=========================================="
echo "  Video Kamba: COCO -> YTB+DAV joint FT"
echo "  Checkpoint: $CKPT"
echo "  Model     : vision_mamba_tiny_sota_light"
echo "  SSM Core  : DiagonalKANSSMCore"
echo "  Datamodule: ytv_dav_joint (DAVIS 25% / YTB 75%)"
echo "  Epochs    : 50"
echo "  Node      : $(hostname)"
echo "  Start     : $(date)"
echo "=========================================="

python train.py \
    model=vision_mamba_tiny_sota_light \
    datamodule=ytv_dav_joint \
    +pretrained_weights="$CKPT" \
    ++trainer.max_epochs=50 \
    ++trainer.accumulate_grad_batches=2 \
    ++trainer.limit_train_batches=3500 \
    ++logger.name="ft_coco_ytbdav_50ep_sota_light_v3" \
    ++logger.tags="[diagonal-kan,coco-pretrain,ytb_dav_joint,lightweight,gate-passed]" \
    ++callbacks.model_checkpoint.monitor=val_J_and_F \
    ++callbacks.model_checkpoint.mode=max \
    ++model.scheduled_sampling_start=0.3 \
    ++model.scheduled_sampling_end=0.7 \
    ++model.scheduled_sampling_warmup_epochs=10

echo ""
echo "=========================================="
echo "  Fine-tuning finished at $(date)"
echo "  Check Comet for run: ft_coco_ytbdav_50ep_sota_light_v3"
echo "=========================================="
